# Generated by Django 4.2 on 2023-04-17 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('happy_home', '0003_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('rating', models.IntegerField(default=5)),
                ('text', models.CharField(blank=True, max_length=1000)),
                ('created', models.DateField(auto_now=True)),
                ('provider_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='happy_home.provider')),
                ('user_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='happy_home.consumer')),
            ],
        ),
    ]
