# Generated by Django 4.2 on 2023-04-17 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('happy_home', '0004_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
