# Generated by Django 4.2 on 2023-04-17 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('happy_home', '0006_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='happy_home.category')),
                ('provider_id', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='happy_home.provider')),
            ],
        ),
    ]
