# Generated by Django 4.2 on 2023-04-19 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happy_home', '0007_classification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classification',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='classification',
            name='provider_id',
        ),
        migrations.AddField(
            model_name='consumer',
            name='cleaning',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='consumer',
            name='electrical',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='consumer',
            name='improvement',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='consumer',
            name='landscape',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='consumer',
            name='plumbing',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Classification',
        ),
    ]
