# Generated by Django 4.2 on 2023-04-19 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happy_home', '0008_remove_classification_category_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumer',
            name='cleaning',
        ),
        migrations.RemoveField(
            model_name='consumer',
            name='electrical',
        ),
        migrations.RemoveField(
            model_name='consumer',
            name='improvement',
        ),
        migrations.RemoveField(
            model_name='consumer',
            name='landscape',
        ),
        migrations.RemoveField(
            model_name='consumer',
            name='plumbing',
        ),
        migrations.AddField(
            model_name='provider',
            name='cleaning',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='provider',
            name='electrical',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='provider',
            name='improvement',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='provider',
            name='landscape',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='provider',
            name='plumbing',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
