# Generated by Django 4.2 on 2023-04-22 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happy_home', '0009_remove_consumer_cleaning_remove_consumer_electrical_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='rating',
            name='title',
            field=models.CharField(default='', max_length=30),
        ),
    ]
