# Generated by Django 4.2 on 2023-04-22 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('happy_home', '0010_alter_rating_rating_alter_rating_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='provider_id',
            new_name='provider',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='user_id',
            new_name='user',
        ),
    ]
