# Generated by Django 4.2 on 2023-04-22 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('happy_home', '0011_rename_provider_id_rating_provider_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='happy_home.provider'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='title',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='happy_home.consumer'),
        ),
    ]
