# Generated by Django 4.2 on 2023-04-22 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('happy_home', '0012_alter_rating_provider_alter_rating_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=30)),
                ('rating', models.FloatField(default=1)),
                ('text', models.CharField(blank=True, max_length=1000)),
                ('created', models.DateField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='happy_home.provider')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='happy_home.consumer')),
            ],
        ),
    ]
