# Generated by Django 4.2 on 2023-04-22 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('happy_home', '0013_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='user',
            new_name='consumer',
        ),
    ]
