# Generated by Django 4.2 on 2023-04-22 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happy_home', '0015_consumer_user_provider_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='consumer',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='provider',
            field=models.IntegerField(null=True),
        ),
    ]
